name: "Deploy"

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy-x64_86:
    runs-on: 	ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: insightsengineering/disk-space-reclaimer@v1
      with:
        swap-storage: false
    - uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:phoenix-ci
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: |
        mkdir -p ~/.ssh
        echo "Host *" >> ~/.ssh/config
        echo "    StrictHostKeyChecking=no" >> ~/.ssh/config
        echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config
    - uses: nixbuild/nix-quick-install-action@v30
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-x86_64-${{ hashFiles('**.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-x86_64-
        gc-max-store-size: 5G
    - uses: cachix/cachix-action@v14
      with:
        name: phoenix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: nicknovitski/nix-develop@v1
    - run: for host in euler; do deploy -sk .#$host 2>&1 | ack --passthru --nocolor "Copying profile" || exit 1; done

  deploy-aarch64:
    runs-on: 	ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: insightsengineering/disk-space-reclaimer@v1
      with:
        swap-storage: false
    - uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:phoenix-ci
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: |
        mkdir -p ~/.ssh
        echo "Host *" >> ~/.ssh/config
        echo "    StrictHostKeyChecking=no" >> ~/.ssh/config
        echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config
    - uses: nixbuild/nix-quick-install-action@v30
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-arm64-${{ hashFiles('**.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-arm64-
        gc-max-store-size: 5G
    - uses: cachix/cachix-action@v14
      with:
        name: phoenix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: nicknovitski/nix-develop@v1
    - run: for host in euclid; do deploy -sk .#$host 2>&1 | ack --passthru --nocolor "Copying profile" || exit 1; done