name: "Deploy"
on:
  pull_request:
  push:
jobs:
  deploy-x64_86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: phoenix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: nicknovitski/nix-develop@v1
    - run: for host in euler; do deploy .#$host; done
  deploy-aarch64:
    runs-on: ubuntu-latest-arm64
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: phoenix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: nicknovitski/nix-develop@v1
    - run: for host in euclid; do deploy .#$host; done