name: "Deploy"
on:
  pull_request:
  push:
jobs:
  deploy-x64_86:
    runs-on: 	ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v30
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-x86_64-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-x86_64-
    - uses: cachix/cachix-action@v14
      with:
        name: phoenix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: nicknovitski/nix-develop@v1
    - run: for host in euler; do deploy .#$host 2>&1 | ack --passthru --nocolor "Copying profile" || exit 1; done
  deploy-aarch64:
    runs-on: 	ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v30
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-arm64-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-arm64-
    - uses: cachix/cachix-action@v14
      with:
        name: phoenix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: nicknovitski/nix-develop@v1
    - run: for host in euclid; do deploy .#$host 2>&1 | ack --passthru --nocolor "Copying profile" || exit 1; done